/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import java.sql.ResultSet;
import dao.AnggotaDAO;
import dao.BukuDAO;
import dao.PeminjamanDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.time.DateTimeException;
import javax.swing.JFrame;
import session.Session;
/**
 *
 * @author Lenovo
 */
public class FormPeminjaman extends javax.swing.JFrame {
    
    private AnggotaDAO anggotaDAO = new AnggotaDAO();
    private BukuDAO bukuDAO = new BukuDAO();
    private PeminjamanDAO peminjamanDAO = new PeminjamanDAO();
    
    private int idPinjam = 0;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPeminjaman.class.getName());

    /**
     * Creates new form FormPeminjaman
     */
    public FormPeminjaman() {
        initComponents();
        
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        tblPeminjaman.setDefaultEditor(Object.class, null);
        
        loadComboAnggota();
        loadComboBuku();
        loadTablePeminjaman();
    }

    private void loadComboAnggota(){
        
        try{
  
            cmbAnggota.removeAllItems();
        
            ResultSet rs = anggotaDAO.getAllAnggota();
        
            while(rs.next()){
                cmbAnggota.addItem(
                        rs.getInt("id_anggota") + " - " + rs.getString("nama")
                );
                
            }
            
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());
        }
    }
    
    private void loadComboBuku(){
        try{
            cmbBuku.removeAllItems();
            
            ResultSet rs = bukuDAO.getAllBuku();
            
            while (rs.next()){
                cmbBuku.addItem(
                        rs.getInt("id_buku") + " - " + rs.getString("judul")
                );
            }
            
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());
        }
    }
    
    private void loadTablePeminjaman(){
        DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("ID");
        model.addColumn("Anggota");
        model.addColumn("Buku");
        model.addColumn("Tanggal Pinjam");
        model.addColumn("Tanggal Kembali");
        model.addColumn("status");
        
        try{
            ResultSet rs = peminjamanDAO.getAllPeminjaman();
            
            while (rs.next()){
                
                model.addRow(new Object[]{
                    rs.getInt("id_pinjam"),
                    rs.getString("nama"),
                    rs.getString("judul"),
                    rs.getString("tanggal_pinjam"),
                    rs.getString("tanggal_kembali"),
                    rs.getString("status")
                });
                
            }
            
            tblPeminjaman.setModel(model);
            
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());
            
        }
    }
    
    private void cariData(){
        
        DefaultTableModel model = (DefaultTableModel) tblPeminjaman.getModel();
        
        model.setRowCount(0);
        
        try{
            
            ResultSet rs = peminjamanDAO.cariPeminjaman(txtCari.getText());
            
            while(rs.next()){
                
                model.addRow(new Object[]{
                    rs.getInt("id_pinjam"),
                    rs.getString("nama"),
                    rs.getString("judul"),
                    rs.getString("tanggal_pinjam"),
                    rs.getString("tanggal_kembali"),
                    rs.getString("status")
                });
                
            }
            
        }catch(Exception e){
            System.out.println("Error cari: " + e.getMessage());
        }
        
    }
    
    private void resetForm(){
        
        cmbAnggota.setSelectedIndex(0);
        cmbBuku.setSelectedIndex(0);
        
        txtTanggalPinjam.setText("");
        txtTanggalKembali.setText("");
        txtCari.setText("");
        
        tblPeminjaman.clearSelection();
        
        idPinjam = 0;
        
        loadTablePeminjaman();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbAnggota = new javax.swing.JComboBox<>();
        cmbBuku = new javax.swing.JComboBox<>();
        txtTanggalPinjam = new javax.swing.JTextField();
        txtTanggalKembali = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPeminjaman = new javax.swing.JTable();
        btnKembalikan = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATA PEMINJAMAN");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Anggota :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Buku :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Tanggal Pinjam :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Tanggal Kembali :");

        cmbAnggota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbAnggota.addActionListener(this::cmbAnggotaActionPerformed);

        cmbBuku.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtTanggalPinjam.addActionListener(this::txtTanggalPinjamActionPerformed);

        txtTanggalKembali.addActionListener(this::txtTanggalKembaliActionPerformed);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Cari :");

        txtCari.addActionListener(this::txtCariActionPerformed);
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(this::btnKeluarActionPerformed);

        tblPeminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Anggota", "Tanggal Pinjam", "Tanggal Kembali", "Status"
            }
        ));
        tblPeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPeminjamanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPeminjaman);

        btnKembalikan.setText("Kembalikan");
        btnKembalikan.addActionListener(this::btnKembalikanActionPerformed);

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSimpan)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapus)
                                .addGap(18, 18, 18)
                                .addComponent(btnKembalikan)
                                .addGap(26, 26, 26)
                                .addComponent(btnReset)
                                .addGap(18, 18, 18)
                                .addComponent(btnKeluar)
                                .addGap(18, 18, 18)
                                .addComponent(btnKembali))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(txtTanggalPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5)
                                        .addComponent(txtTanggalKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6)
                                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmbBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                    .addComponent(cmbAnggota, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTanggalPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTanggalKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnUpdate)
                    .addComponent(btnHapus)
                    .addComponent(btnKembalikan)
                    .addComponent(btnReset)
                    .addComponent(btnKeluar)
                    .addComponent(btnKembali))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAnggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbAnggotaActionPerformed

    private void txtTanggalKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTanggalKembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTanggalKembaliActionPerformed

    private void txtTanggalPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTanggalPinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTanggalPinjamActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        
        if(txtTanggalPinjam.getText().trim().isEmpty()||
            txtTanggalKembali.getText().trim().isEmpty()){
            
            JOptionPane.showMessageDialog(this, "Tanggal pinjam dan tanggal kembali harus diisi!");
            
            return;
        }
        
        try{
            String anggota = cmbAnggota.getSelectedItem().toString();
            int idAnggota = Integer.parseInt(anggota.split(" - ")[0]);
            
            String buku = cmbBuku.getSelectedItem().toString();
            int idBuku = Integer.parseInt(buku.split(" - ")[0]);
            
            int stok = bukuDAO.getStok(idBuku);
            
            if(stok <= 0){
                JOptionPane.showMessageDialog(this, "Stok buku habis, tidak bisa dipinjam!");
                
                return;
            }
            
            String tglPinjam = txtTanggalPinjam.getText();
            String tglKembali = txtTanggalKembali.getText();
            
            try{
                
                LocalDate tanggalPinjam = LocalDate.parse(tglPinjam);
                LocalDate tanggalKembali = LocalDate.parse(tglKembali);
                
                if(tanggalKembali.isBefore(tanggalPinjam)){
                    JOptionPane.showMessageDialog(this, "Tanggal kembali tidak boleh sebelum tanggal pinjam!");
                    return;
                    
                }
            }catch(DateTimeException e){
                
                JOptionPane.showMessageDialog(this, "Format tanggal harus YYYY-MM-DD!");
                return;
            }
            
            String status = "Dipinjam";
            
            peminjamanDAO.insertPeminjaman(idAnggota, idBuku, tglPinjam, tglKembali, status);
            
            bukuDAO.KurangiStok(idBuku);
            
            resetForm();
            
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());    
        }
    
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void tblPeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPeminjamanMouseClicked
        
        int baris = tblPeminjaman.getSelectedRow();
        
        idPinjam = Integer.parseInt(tblPeminjaman.getValueAt(baris, 0).toString());
        
        try{
            ResultSet rs = peminjamanDAO.getPeminjamanById(idPinjam);
            
            if(rs.next()){
                
                int idAnggota = rs.getInt("id_anggota");
                int idBuku = rs.getInt("id_buku");
                
                txtTanggalPinjam.setText(rs.getString("tanggal_pinjam"));
                txtTanggalKembali.setText(rs.getString("tanggal_kembali"));
                
            
                for(int i = 0; i < cmbAnggota.getItemCount(); i++){
                
                    String item = cmbAnggota.getItemAt(i);
                
                    if(item.startsWith(idAnggota + " -")){
                        cmbAnggota.setSelectedIndex(i);
                        break;
                    }
                }
                
                for(int i = 0; i < cmbBuku.getItemCount(); i++){
                    String item = cmbBuku.getItemAt(i);
                    
                    if(item.startsWith(idBuku + " -")){
                        cmbBuku.setSelectedIndex(i);
                        break;
                    }
                }
            }
        }catch(Exception e){
            System.out.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_tblPeminjamanMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        
        try{
            
            String anggota = cmbAnggota.getSelectedItem().toString();
            int idAnggota = Integer.parseInt(anggota.split(" - ")[0]);
            
            String buku = cmbBuku.getSelectedItem().toString();
            int idBuku = Integer.parseInt(buku.split(" - ")[0]);
            
            String tglPinjam = txtTanggalPinjam.getText();
            String tglKembali = txtTanggalKembali.getText();
            
            String status = "Dipinjam";
            
            peminjamanDAO.updatePeminjaman(idPinjam, idAnggota, idBuku, tglPinjam, tglKembali, status);
            
            resetForm();
            
            JOptionPane.showMessageDialog(this, "Data berhasil diupdate!");
            
        }catch(Exception e){
            
            System.out.println("Error: " + e.getMessage());
            
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        
        if(idPinjam == 0){
            JOptionPane.showMessageDialog(this, "Pilih data yang akan dihapus!");
            
            return;
        }
        
        int konfirmasi = JOptionPane.showConfirmDialog(this, "yakin ingin menghapus data ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
        
        if(konfirmasi != JOptionPane.YES_OPTION){
            return;
        }
        
        peminjamanDAO.deletePeminjaman(idPinjam);
            
        loadTablePeminjaman();
            
        resetForm();
            
        JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
    
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKembalikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembalikanActionPerformed
        
        try{
            
            ResultSet rs = peminjamanDAO.getPeminjamanById(idPinjam);
            
            if(rs.next()){
                
                int idBuku = rs.getInt("id_buku");
                
                String status = rs.getString("status");
                
                if(status.equals("Dikembalikan")){
                    JOptionPane.showMessageDialog(this, "Buku ini sudah dikembalikan!");
                    
                    return;
                }
                
                peminjamanDAO.kembalikanBuku(idPinjam);
                
                bukuDAO.tambahStok(idBuku);
                
                loadTablePeminjaman();
                
                resetForm();
                
                JOptionPane.showMessageDialog(this, "Buku berhasil dikembalikan");
                
                
            }
        }catch(Exception e){
            
            System.out.println("Error: " + e.getMessage());
            
        }
    }//GEN-LAST:event_btnKembalikanActionPerformed

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        cariData();
    }//GEN-LAST:event_txtCariKeyReleased

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        resetForm();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Yakin mau Keluar?", "Konfirmasi", javax.swing.JOptionPane.YES_NO_OPTION);
        
        if(confirm == javax.swing.JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        new MenuUtama(Session.username, Session.role).setVisible(true);
        
        dispose();
        
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormPeminjaman().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnKembalikan;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbAnggota;
    private javax.swing.JComboBox<String> cmbBuku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblPeminjaman;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtTanggalKembali;
    private javax.swing.JTextField txtTanggalPinjam;
    // End of variables declaration//GEN-END:variables
}
