/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import dao.BukuDAO;
import dao.AnggotaDAO;
import dao.PeminjamanDAO;
import javax.swing.JFrame;
import session.Session;

/**
 *
 * @author Lenovo
 */
public class MenuUtama extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuUtama.class.getName());
    private BukuDAO bukuDAO = new BukuDAO();
    private AnggotaDAO anggotaDAO = new AnggotaDAO();
    private PeminjamanDAO peminjamanDAO = new PeminjamanDAO();
    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        
        setExtendedState(JFrame.MAXIMIZED_BOTH);

    }
    
    public MenuUtama(String username, String role){
        initComponents();
        
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

        lblWelcome.setText("Selamat Datang, " + username + "!");
        
        loadDashboard();
        
        if("Petugas".equals(role)){
            btnTambahAkun.setVisible(false);
        }
        
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudul = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        btnBuku = new javax.swing.JButton();
        btnAnggota = new javax.swing.JButton();
        btnPeminjaman = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnTambahAkun = new javax.swing.JButton();
        lblTotalPeminjaman = new javax.swing.JLabel();
        lblTotalAnggota = new javax.swing.JLabel();
        lblTotalBuku = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblJudul.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        lblJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudul.setText("APLIKASI PERPUSTAKAAN");

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnBuku.setText("Data Buku");
        btnBuku.addActionListener(this::btnBukuActionPerformed);

        btnAnggota.setText("Data Anggota");
        btnAnggota.addActionListener(this::btnAnggotaActionPerformed);

        btnPeminjaman.setText("Data Peminjaman");
        btnPeminjaman.addActionListener(this::btnPeminjamanActionPerformed);

        btnLogout.setText("Logout");
        btnLogout.addActionListener(this::btnLogoutActionPerformed);

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(this::btnKeluarActionPerformed);

        btnTambahAkun.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnTambahAkun.setText("Tambah akun");
        btnTambahAkun.addActionListener(this::btnTambahAkunActionPerformed);

        lblTotalPeminjaman.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotalPeminjaman.setText("Total Peminjaman  :  0");

        lblTotalAnggota.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotalAnggota.setText("Total Anggota       :  0");

        lblTotalBuku.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotalBuku.setText("Total Buku             :  0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTotalBuku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAnggota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblJudul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTambahAkun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(302, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotalAnggota)
                            .addComponent(lblTotalPeminjaman))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWelcome)
                .addGap(18, 18, 18)
                .addComponent(btnBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTambahAkun, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalBuku)
                        .addGap(19, 19, 19)))
                .addComponent(lblTotalAnggota)
                .addGap(18, 18, 18)
                .addComponent(lblTotalPeminjaman)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBukuActionPerformed
        new FormBuku().setVisible(true);
        
        dispose();
        
    }//GEN-LAST:event_btnBukuActionPerformed

    private void btnAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnggotaActionPerformed
        new FormAnggota().setVisible(true);
        
        dispose();
        
    }//GEN-LAST:event_btnAnggotaActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        
        int pilih = JOptionPane.showConfirmDialog(this, "Yakin ingin LogOut?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        
        if(pilih == JOptionPane.YES_OPTION){
            
            new FormLogin().setVisible(true);
            
            dispose();
            
        }
        
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        int pilih = JOptionPane.showConfirmDialog(this, "Yakin ingin keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        
        if(pilih == JOptionPane.YES_OPTION){
            System.exit(0);
            
        }
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeminjamanActionPerformed
        new FormPeminjaman().setVisible(true);
        
        dispose();
        
    }//GEN-LAST:event_btnPeminjamanActionPerformed

    private void btnTambahAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahAkunActionPerformed
        
        FormRegister register = new FormRegister(this);
        
        register.setVisible(true);
        
        this.setVisible(false);
        
    }//GEN-LAST:event_btnTambahAkunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuUtama().setVisible(true));
    }
    
    private void loadDashboard(){
        
        lblTotalBuku.setText("Total Buku : " + bukuDAO.getTotalBuku());
        
        lblTotalAnggota.setText("Total Anggota : " + anggotaDAO.getTotalAnggota());
        
        lblTotalPeminjaman.setText("Total Peminjaman : " + peminjamanDAO.getTotalPeminjaman());
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnggota;
    private javax.swing.JButton btnBuku;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPeminjaman;
    private javax.swing.JButton btnTambahAkun;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblTotalAnggota;
    private javax.swing.JLabel lblTotalBuku;
    private javax.swing.JLabel lblTotalPeminjaman;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
